/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mart_swing;

import java.awt.geom.CubicCurve2D;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sunsythorng
 */
public class super_mart extends javax.swing.JFrame {
    DefaultTableModel model;
    DecimalFormat df=new DecimalFormat("####0.00");
    /**
     * Creates new form super_mart
     */
    public super_mart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void Item(){
        // Kat String
//       double sum=0;
//       for(int i=0;i<table1.getRowCount();i++){
//           String t=table1.getValueAt(i,2).toString();
//           t=t.substring(0,t.length()-1);   // 0.5
//           double price1=Double.parseDouble(t);
//           sum=sum+price1;
//       }

        // + 
        double sum=0;
         for (int i=0;i<table1.getRowCount();i++){
            sum=sum+Double.parseDouble(table1.getValueAt(i,2).toString());
         }
        txtSub.setText(Double.toString(sum));
        // ----------------------------------------------------------------
        
        double Csub=Double.parseDouble(txtSub.getText());
        double  CTax= (Csub*3.9)/100;
        
        String s=String.format("%.2f $", CTax);
        txtTax.setText(s);
        
        String a=String.format("%.2f $", Csub);
        txtSub.setText(a);
        
        String c=String.format("%.2f $", Csub+CTax);
        txtTotal.setText(c);
        
        double t=(Csub+CTax)*4000;
        
        String d=String.format("%.2f R",t);
        txtRiel.setText(d);
        
        // or  use format 
//         txtTotal.setText(String.valueOf(df.format(Csub+CTax)+"$"));
    }
    
    public void change(){
        double sum1=0;
        double tax=3.9;
        double cash=Double.parseDouble(txtCash.getText());
        
        for (int i=0;i<table1.getRowCount();i++){
             sum1=(sum1+Double.parseDouble(table1.getValueAt(i,2).toString()));
         }
        
        double Ctax=(sum1 * 3.9)/100;
        double Ccash= ( cash- (sum1+Ctax) );
         
        String a=String.format("%.2f $",Ccash);
        txtChange.setText(a);
        
        // Riel
        double t=( cash- (sum1+Ctax) )*4000;
        String d=String.format("%.2f R",t);
        txtChange1.setText(d);
        
// Convert   kat $ jeng pi total 
//        double ca=Double.parseDouble(txtCash.getText());
//        
//        String s=String.valueOf(txtTotal.getText());
//        s=s.substring(0,s.length()-1);
//        double to=Double.parseDouble(s);
//        
//        double ca1=ca-to;
//        
//        txtChange.setText(String.valueOf(df.format(ca1)));
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt6 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        btC = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        bt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        c1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        c2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        c3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        c4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        c5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        c6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        c7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        c8 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        c9 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        c10 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        c11 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        c12 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        c13 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        c14 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        c15 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        c16 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        c17 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        c18 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jb1 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtSub = new javax.swing.JTextField();
        txtTax = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtChange = new javax.swing.JTextField();
        txtCash = new javax.swing.JTextField();
        cbpay = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        btexit = new javax.swing.JButton();
        btPay = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        btprint = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        txtcode = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtRiel = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtChange1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 759));
        setSize(new java.awt.Dimension(1400, 807));
        getContentPane().setLayout(null);

        bt6.setBackground(new java.awt.Color(255, 255, 255));
        bt6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        bt6.setForeground(new java.awt.Color(0, 0, 0));
        bt6.setText("6");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        getContentPane().add(bt6);
        bt6.setBounds(160, 130, 50, 60);

        bt1.setBackground(new java.awt.Color(255, 255, 255));
        bt1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        bt1.setForeground(new java.awt.Color(0, 0, 0));
        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(40, 60, 50, 60);

        bt2.setBackground(new java.awt.Color(255, 255, 255));
        bt2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        bt2.setForeground(new java.awt.Color(0, 0, 0));
        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(100, 60, 50, 60);

        bt3.setBackground(new java.awt.Color(255, 255, 255));
        bt3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        bt3.setForeground(new java.awt.Color(0, 0, 0));
        bt3.setText("3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3);
        bt3.setBounds(160, 60, 50, 60);

        bt4.setBackground(new java.awt.Color(255, 255, 255));
        bt4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        bt4.setForeground(new java.awt.Color(0, 0, 0));
        bt4.setText("4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        getContentPane().add(bt4);
        bt4.setBounds(40, 130, 50, 60);

        bt5.setBackground(new java.awt.Color(255, 255, 255));
        bt5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        bt5.setForeground(new java.awt.Color(0, 0, 0));
        bt5.setText("5");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        getContentPane().add(bt5);
        bt5.setBounds(100, 130, 50, 60);

        bt9.setBackground(new java.awt.Color(255, 255, 255));
        bt9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        bt9.setForeground(new java.awt.Color(0, 0, 0));
        bt9.setText("9");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        getContentPane().add(bt9);
        bt9.setBounds(160, 200, 50, 60);

        bt7.setBackground(new java.awt.Color(255, 255, 255));
        bt7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        bt7.setForeground(new java.awt.Color(0, 0, 0));
        bt7.setText("7");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        getContentPane().add(bt7);
        bt7.setBounds(40, 200, 50, 60);

        bt8.setBackground(new java.awt.Color(255, 255, 255));
        bt8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        bt8.setForeground(new java.awt.Color(0, 0, 0));
        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        getContentPane().add(bt8);
        bt8.setBounds(100, 200, 50, 60);

        btC.setBackground(new java.awt.Color(255, 255, 255));
        btC.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btC.setForeground(new java.awt.Color(0, 0, 0));
        btC.setText("C");
        btC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCActionPerformed(evt);
            }
        });
        getContentPane().add(btC);
        btC.setBounds(160, 270, 50, 60);

        bt0.setBackground(new java.awt.Color(255, 255, 255));
        bt0.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        bt0.setForeground(new java.awt.Color(0, 0, 0));
        bt0.setText("0");
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });
        getContentPane().add(bt0);
        bt0.setBounds(40, 270, 50, 60);

        bt.setBackground(new java.awt.Color(255, 255, 255));
        bt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        bt.setForeground(new java.awt.Color(0, 0, 0));
        bt.setText(".");
        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });
        getContentPane().add(bt);
        bt.setBounds(100, 270, 50, 60);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "QTY", "Price"
            }
        ));
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(270, 20, 330, 320);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/sting.jpeg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 40, 85, 85);

        c1.setMinimumSize(new java.awt.Dimension(85, 85));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(680, 40, 90, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/sprite.jpeg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(790, 40, 85, 85);

        c2.setMinimumSize(new java.awt.Dimension(85, 85));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(790, 40, 90, 90);

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/co.jpeg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(910, 40, 85, 85);

        c3.setMinimumSize(new java.awt.Dimension(85, 85));
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        getContentPane().add(c3);
        c3.setBounds(910, 40, 90, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/soda.jpeg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1030, 40, 85, 85);

        c4.setMinimumSize(new java.awt.Dimension(85, 85));
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        getContentPane().add(c4);
        c4.setBounds(1030, 40, 90, 90);

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/pespi.jpeg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1150, 40, 85, 85);

        c5.setMinimumSize(new java.awt.Dimension(85, 85));
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });
        getContentPane().add(c5);
        c5.setBounds(1150, 40, 90, 90);

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/bz18041.jpeg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1270, 40, 85, 85);

        c6.setMinimumSize(new java.awt.Dimension(85, 85));
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });
        getContentPane().add(c6);
        c6.setBounds(1270, 40, 90, 90);

        jLabel9.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/bz18041.jpeg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1270, 40, 85, 85);

        jLabel10.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/HAK-00008.png")); // NOI18N
        jLabel10.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel10AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(680, 160, 85, 85);

        c7.setMinimumSize(new java.awt.Dimension(85, 85));
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });
        getContentPane().add(c7);
        c7.setBounds(680, 160, 90, 90);

        jLabel12.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/Anjedhg2zlmb1monjy8sc.jpeg")); // NOI18N
        jLabel12.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel12AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(790, 160, 90, 90);

        c8.setMinimumSize(new java.awt.Dimension(85, 85));
        c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c8ActionPerformed(evt);
            }
        });
        getContentPane().add(c8);
        c8.setBounds(790, 160, 90, 90);

        jLabel13.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/grean.png")); // NOI18N
        jLabel13.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel13AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(910, 160, 85, 85);

        c9.setMinimumSize(new java.awt.Dimension(85, 85));
        c9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c9ActionPerformed(evt);
            }
        });
        getContentPane().add(c9);
        c9.setBounds(910, 160, 90, 90);

        jLabel14.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/HBH-00007.png")); // NOI18N
        jLabel14.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel14AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel14);
        jLabel14.setBounds(1030, 160, 85, 77);

        c10.setMinimumSize(new java.awt.Dimension(85, 85));
        c10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c10ActionPerformed(evt);
            }
        });
        getContentPane().add(c10);
        c10.setBounds(1030, 160, 90, 90);

        jLabel15.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/amazon.png")); // NOI18N
        jLabel15.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel15AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1150, 160, 90, 90);

        c11.setMinimumSize(new java.awt.Dimension(85, 85));
        c11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c11ActionPerformed(evt);
            }
        });
        getContentPane().add(c11);
        c11.setBounds(1150, 160, 90, 90);

        jLabel16.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/A7EF1A059-0BEED71BCD8D.jpeg")); // NOI18N
        jLabel16.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel16AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1270, 160, 85, 85);

        c12.setMinimumSize(new java.awt.Dimension(85, 85));
        c12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c12ActionPerformed(evt);
            }
        });
        getContentPane().add(c12);
        c12.setBounds(1270, 160, 90, 90);

        jLabel17.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/Afa3a6370-907f-4d55-a5b1-ebfac60f4fb1.png")); // NOI18N
        jLabel17.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel17AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel17);
        jLabel17.setBounds(680, 270, 85, 85);

        c13.setMinimumSize(new java.awt.Dimension(85, 85));
        c13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c13ActionPerformed(evt);
            }
        });
        getContentPane().add(c13);
        c13.setBounds(680, 270, 90, 90);

        jLabel19.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/ATofu-Burger.png")); // NOI18N
        jLabel19.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel19AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel19);
        jLabel19.setBounds(790, 270, 85, 85);

        c14.setMinimumSize(new java.awt.Dimension(85, 85));
        c14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c14ActionPerformed(evt);
            }
        });
        getContentPane().add(c14);
        c14.setBounds(790, 270, 90, 90);

        jLabel21.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/BSpaghetti-No-Background-Clip-Art.png")); // NOI18N
        jLabel21.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel21AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel21);
        jLabel21.setBounds(910, 270, 85, 85);

        c15.setMinimumSize(new java.awt.Dimension(85, 85));
        c15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c15ActionPerformed(evt);
            }
        });
        getContentPane().add(c15);
        c15.setBounds(910, 270, 90, 90);

        jLabel23.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/Cspaghetti-png-transparent-image.png")); // NOI18N
        jLabel23.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel23AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel23);
        jLabel23.setBounds(1030, 270, 85, 85);

        c16.setMinimumSize(new java.awt.Dimension(85, 85));
        c16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c16ActionPerformed(evt);
            }
        });
        getContentPane().add(c16);
        c16.setBounds(1030, 270, 90, 90);

        jLabel25.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/a222222.png")); // NOI18N
        jLabel25.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel25AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel25);
        jLabel25.setBounds(1140, 270, 100, 85);

        c17.setMinimumSize(new java.awt.Dimension(85, 85));
        c17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c17ActionPerformed(evt);
            }
        });
        getContentPane().add(c17);
        c17.setBounds(1150, 270, 90, 90);

        jLabel27.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/akfc-80-piece-popcorn-chicken-bucket-1583144503.png")); // NOI18N
        jLabel27.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel27AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel27);
        jLabel27.setBounds(1270, 270, 85, 85);

        c18.setMinimumSize(new java.awt.Dimension(85, 85));
        c18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c18ActionPerformed(evt);
            }
        });
        getContentPane().add(c18);
        c18.setBounds(1270, 270, 90, 90);

        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2);
        jLabel2.setBounds(630, 20, 740, 370);

        jb1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jb1.setForeground(new java.awt.Color(0, 0, 0));
        jb1.setText("Total  (R):");
        getContentPane().add(jb1);
        jb1.setBounds(70, 680, 110, 20);

        jLabel29.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Sub Total: ");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(70, 540, 110, 20);

        jLabel30.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Tax :");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(70, 590, 110, 20);

        jLabel31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel31);
        jLabel31.setBounds(20, 50, 220, 290);

        txtTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtTotal.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        getContentPane().add(txtTotal);
        txtTotal.setBounds(180, 630, 210, 34);

        txtSub.setBackground(new java.awt.Color(255, 255, 255));
        txtSub.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubActionPerformed(evt);
            }
        });
        getContentPane().add(txtSub);
        txtSub.setBounds(180, 530, 210, 34);

        txtTax.setBackground(new java.awt.Color(255, 255, 255));
        txtTax.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        getContentPane().add(txtTax);
        txtTax.setBounds(180, 580, 210, 34);

        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 500, 410, 220);

        jLabel32.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Change (R):");
        jLabel32.setToolTipText("");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(500, 680, 160, 22);

        jLabel33.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Payment Method :");
        jLabel33.setToolTipText("");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(490, 530, 180, 22);

        jLabel34.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Cash :");
        jLabel34.setToolTipText("");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(500, 580, 180, 22);

        txtChange.setBackground(new java.awt.Color(255, 255, 255));
        txtChange.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtChange.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtChange);
        txtChange.setBounds(670, 620, 250, 40);

        txtCash.setBackground(new java.awt.Color(255, 255, 255));
        txtCash.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtCash.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCash);
        txtCash.setBounds(670, 570, 250, 40);

        cbpay.setBackground(new java.awt.Color(255, 255, 255));
        cbpay.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        cbpay.setForeground(new java.awt.Color(0, 0, 0));
        cbpay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "US", "Riel" }));
        cbpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpayActionPerformed(evt);
            }
        });
        getContentPane().add(cbpay);
        cbpay.setBounds(670, 515, 250, 40);

        jLabel35.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel35);
        jLabel35.setBounds(480, 500, 470, 220);

        btexit.setBackground(new java.awt.Color(255, 51, 51));
        btexit.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btexit.setForeground(new java.awt.Color(0, 0, 0));
        btexit.setText("Exit");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });
        getContentPane().add(btexit);
        btexit.setBounds(1030, 640, 280, 40);

        btPay.setBackground(new java.awt.Color(255, 255, 255));
        btPay.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btPay.setForeground(new java.awt.Color(0, 0, 0));
        btPay.setText("Pay");
        btPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPayActionPerformed(evt);
            }
        });
        getContentPane().add(btPay);
        btPay.setBounds(1030, 510, 130, 40);

        btReset.setBackground(new java.awt.Color(255, 255, 255));
        btReset.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btReset.setForeground(new java.awt.Color(0, 0, 0));
        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        getContentPane().add(btReset);
        btReset.setBounds(1180, 510, 130, 40);

        btprint.setBackground(new java.awt.Color(255, 255, 255));
        btprint.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btprint.setForeground(new java.awt.Color(0, 0, 0));
        btprint.setText("Print");
        btprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprintActionPerformed(evt);
            }
        });
        getContentPane().add(btprint);
        btprint.setBounds(1030, 570, 130, 40);

        btRemove.setBackground(new java.awt.Color(255, 255, 255));
        btRemove.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btRemove.setForeground(new java.awt.Color(0, 0, 0));
        btRemove.setText("remove");
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btRemove);
        btRemove.setBounds(1180, 570, 130, 40);

        jLabel37.setToolTipText("");
        jLabel37.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel37);
        jLabel37.setBounds(980, 500, 370, 220);

        txtcode.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        txtcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtcode);
        txtcode.setBounds(270, 350, 330, 90);

        jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel18);
        jLabel18.setBounds(260, 10, 360, 440);

        jLabel20.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Total ($):");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(70, 640, 110, 20);

        txtRiel.setBackground(new java.awt.Color(255, 255, 255));
        txtRiel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        getContentPane().add(txtRiel);
        txtRiel.setBounds(180, 670, 210, 34);

        jLabel36.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Change ($):");
        jLabel36.setToolTipText("");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(500, 630, 160, 22);

        txtChange1.setBackground(new java.awt.Color(255, 255, 255));
        txtChange1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtChange1.setForeground(new java.awt.Color(0, 0, 0));
        txtChange1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChange1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtChange1);
        txtChange1.setBounds(670, 670, 250, 40);

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("1.5 $");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1170, 140, 40, 15);

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("1.5 $");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(710, 140, 32, 15);

        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("1.6 $");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(810, 140, 51, 15);

        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("1.0 $");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(930, 140, 51, 15);

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("2 $");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(1300, 140, 30, 15);

        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("2 $");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(1060, 140, 30, 15);

        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("2.5 $");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(1290, 250, 40, 15);

        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("2.2 $");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(940, 250, 40, 15);

        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("2.2 $");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(810, 250, 40, 15);

        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("7.5 $");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(1300, 360, 40, 15);

        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("2.2 $");
        getContentPane().add(jLabel43);
        jLabel43.setBounds(1060, 250, 40, 15);

        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("2.5 $");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(710, 250, 40, 15);

        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("2.5 $");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(1180, 250, 40, 15);

        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("4.5 $");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(1060, 360, 40, 15);

        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("5 $");
        getContentPane().add(jLabel47);
        jLabel47.setBounds(710, 360, 30, 15);

        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("5 $");
        getContentPane().add(jLabel48);
        jLabel48.setBounds(820, 360, 30, 15);

        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("5.5 $");
        getContentPane().add(jLabel49);
        jLabel49.setBounds(1180, 360, 40, 15);

        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("5.5 $");
        getContentPane().add(jLabel50);
        jLabel50.setBounds(940, 360, 40, 15);

        jLabel51.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/A22222222.png")); // NOI18N
        getContentPane().add(jLabel51);
        jLabel51.setBounds(420, 0, 980, 810);

        jLabel52.setIcon(new javax.swing.ImageIcon("/Users/sunsythorng/Desktop/Product/A22222222.png")); // NOI18N
        getContentPane().add(jLabel52);
        jLabel52.setBounds(0, 0, 980, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        txtCash.setText(txtCash.getText()+"6");
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        txtCash.setText(txtCash.getText()+"1");
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        txtCash.setText(txtCash.getText()+"2");
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        txtCash.setText(txtCash.getText()+"3");
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        txtCash.setText(txtCash.getText()+"4");
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        txtCash.setText(txtCash.getText()+"5");
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        txtCash.setText(txtCash.getText()+"9");
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        txtCash.setText(txtCash.getText()+"7");
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        txtCash.setText(txtCash.getText()+"8");
    }//GEN-LAST:event_bt8ActionPerformed

    private void btCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCActionPerformed
        txtCash.setText("");
    }//GEN-LAST:event_btCActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        txtCash.setText(txtCash.getText()+"0");
    }//GEN-LAST:event_bt0ActionPerformed

    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
        if(!txtCash.getText().contains(".")){
            txtCash.setText(txtCash.getText()+".");
        }
    }//GEN-LAST:event_btActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
                DefaultTableModel model=(DefaultTableModel) table1.getModel();
                double t=1.6;
                model.addRow(new Object []{"Sprite","1",t});
                Item();
    }//GEN-LAST:event_c2ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
            
            DefaultTableModel model=(DefaultTableModel) table1.getModel();
            
                double t=1.5;
                model.addRow(new Object []{"String","1",t});
                Item();
                 
 //            list_mart obj=new list_mart(a,b, (float) t);
//            list_mart.list.add(obj);

//            for(int i=0;i<list_mart.list.size();i++){
//            }
           

    }//GEN-LAST:event_c1ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        DefaultTableModel model=(DefaultTableModel) table1.getModel();
            
                double t=1.0;
                model.addRow(new Object []{"COCA","1",t});
                Item();
    }//GEN-LAST:event_c3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
                DefaultTableModel model=(DefaultTableModel) table1.getModel();
                double t=2;
                model.addRow(new Object []{"SODA","1",t});
                Item();
    }//GEN-LAST:event_c4ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
                DefaultTableModel model=(DefaultTableModel) table1.getModel();
                double t=1.5;
                model.addRow(new Object []{"Pepsi","1",t});
                Item();
    }//GEN-LAST:event_c5ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
                DefaultTableModel model=(DefaultTableModel) table1.getModel();
                double t=2;
                model.addRow(new Object []{"Fanta","1",t});
                Item();
    }//GEN-LAST:event_c6ActionPerformed

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7ActionPerformed
                DefaultTableModel model=(DefaultTableModel) table1.getModel();
                double t=2.5;
                model.addRow(new Object []{"Blue milk","1",t});
                Item();
    }//GEN-LAST:event_c7ActionPerformed

    private void c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c8ActionPerformed
                DefaultTableModel model=(DefaultTableModel) table1.getModel();
                double t=2.2;
                model.addRow(new Object []{"Red milk","1",t});
                Item();
    }//GEN-LAST:event_c8ActionPerformed

    private void jLabel10AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel10AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10AncestorAdded

    private void jLabel13AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel13AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13AncestorAdded

    private void c9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c9ActionPerformed
                DefaultTableModel model=(DefaultTableModel) table1.getModel();
                double t=2.2;
                model.addRow(new Object []{"Green milk","1",t});
                Item();
    }//GEN-LAST:event_c9ActionPerformed

    private void jLabel14AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel14AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14AncestorAdded

    private void c10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c10ActionPerformed
                 DefaultTableModel model=(DefaultTableModel) table1.getModel();
                double t=2.2;
                model.addRow(new Object []{"Pink milk","1",t});
                Item();
    }//GEN-LAST:event_c10ActionPerformed

    private void jLabel15AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel15AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15AncestorAdded

    private void c11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c11ActionPerformed
                DefaultTableModel model=(DefaultTableModel) table1.getModel();
                double t=2.5;
                model.addRow(new Object []{"Ice Cofe","1",t});
                Item();
    }//GEN-LAST:event_c11ActionPerformed

    private void jLabel16AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel16AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16AncestorAdded

    private void c12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c12ActionPerformed
                DefaultTableModel model=(DefaultTableModel) table1.getModel();
                double t=2.5;
                model.addRow(new Object []{"Cofe","1",t});
                Item();
    }//GEN-LAST:event_c12ActionPerformed

    private void jLabel17AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel17AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17AncestorAdded

    private void c13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c13ActionPerformed
                DefaultTableModel model=(DefaultTableModel) table1.getModel();
                double t=5;
                model.addRow(new Object []{"Pizza","1",t});
                Item();
    }//GEN-LAST:event_c13ActionPerformed

    private void jLabel19AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel19AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19AncestorAdded

    private void c14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c14ActionPerformed
                DefaultTableModel model=(DefaultTableModel) table1.getModel();
                double t=5;
                model.addRow(new Object []{"Burgur","1",t});
                Item();
    }//GEN-LAST:event_c14ActionPerformed

    private void jLabel21AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel21AncestorAdded
                
    }//GEN-LAST:event_jLabel21AncestorAdded

    private void c15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c15ActionPerformed
                DefaultTableModel model=(DefaultTableModel) table1.getModel();
                double t=5.5;
                model.addRow(new Object []{"Spigetti","1",t});
                Item();
    }//GEN-LAST:event_c15ActionPerformed

    private void jLabel23AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel23AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23AncestorAdded

    private void c16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c16ActionPerformed
                DefaultTableModel model=(DefaultTableModel) table1.getModel();
                double t=4.5;
                model.addRow(new Object []{" Top Spigetti","1",t});
                Item();
    }//GEN-LAST:event_c16ActionPerformed

    private void jLabel25AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel25AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25AncestorAdded

    private void c17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c17ActionPerformed
                DefaultTableModel model=(DefaultTableModel) table1.getModel();
                double t=5.5;
                model.addRow(new Object []{"Bay Cha","1",t});
                Item();
    }//GEN-LAST:event_c17ActionPerformed

    private void jLabel27AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel27AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27AncestorAdded

    private void c18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c18ActionPerformed
                DefaultTableModel model=(DefaultTableModel) table1.getModel();
                double t=7.5;
                model.addRow(new Object []{"KFC","1",t});
                Item();
    }//GEN-LAST:event_c18ActionPerformed

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btexitActionPerformed

    private void jLabel12AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel12AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12AncestorAdded

    private void txtSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubActionPerformed

    private void btPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPayActionPerformed
         
       if(cbpay.getSelectedItem().equals("US")){
            change();
       }else{
        double sum1=0;
        double tax=3.9;
        double cash=Double.parseDouble(txtCash.getText());
        
        for (int i=0;i<table1.getRowCount();i++){
             sum1=(sum1+Double.parseDouble(table1.getValueAt(i,2).toString()));
         }
        
        double Ctax=(sum1 * 3.9)/100;
        
        double Ccash= ( cash - ((sum1+Ctax)*4000) );
        
        String a=String.format("%.2f R",Ccash);
        txtChange1.setText(a);
        
        double Ccash1=Ccash/4000;
        
        String b=String.format("%.2f $",Ccash1);
        txtChange.setText(b);
       }
    }//GEN-LAST:event_btPayActionPerformed

    private void cbpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbpayActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
       txtCash.setText("");
       txtChange.setText("");
       txtSub.setText("");
       txtTax.setText("");
       txtTotal.setText("");
       txtRiel.setText("");
       txtChange1.setText("");
       DefaultTableModel model=(DefaultTableModel) table1.getModel();
       model.setRowCount(0);
    }//GEN-LAST:event_btResetActionPerformed

    private void txtChange1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChange1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChange1ActionPerformed

    private void btprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprintActionPerformed
//        MessageFormat header1=new MessageFormat("Printing in progress");
//        MessageFormat foot1=new MessageFormat("Page {0,number,interger");
//        try{
//            table1.print(JTable.PrintMode.NORMAL,header1,foot1);
//        }
//        catch(java.awt.print.PrinterException e){
//            System.err.format("No Printer found", e.getMessage());
//        }

        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        try {
            table1.print(JTable.PrintMode.NORMAL,header,footer);
        } catch (java.awt.print.PrinterException ex) {
            System.err.format("No Printer Found...!", ex.getMessage());
        }
    }//GEN-LAST:event_btprintActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
         DefaultTableModel model=(DefaultTableModel) table1.getModel();
         int remove1=table1.getSelectedRow();
         if(remove1>=0){
             model.removeRow(remove1);
         }
//         model.removeRow(remove1);
         Item();
         
    }//GEN-LAST:event_btRemoveActionPerformed

    private void txtcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(super_mart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(super_mart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(super_mart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(super_mart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new super_mart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt;
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btC;
    private javax.swing.JButton btPay;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btexit;
    private javax.swing.JButton btprint;
    private javax.swing.JButton c1;
    private javax.swing.JButton c10;
    private javax.swing.JButton c11;
    private javax.swing.JButton c12;
    private javax.swing.JButton c13;
    private javax.swing.JButton c14;
    private javax.swing.JButton c15;
    private javax.swing.JButton c16;
    private javax.swing.JButton c17;
    private javax.swing.JButton c18;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton c5;
    private javax.swing.JButton c6;
    private javax.swing.JButton c7;
    private javax.swing.JButton c8;
    private javax.swing.JButton c9;
    private javax.swing.JComboBox<String> cbpay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jb1;
    private javax.swing.JTable table1;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtChange;
    private javax.swing.JTextField txtChange1;
    private javax.swing.JTextField txtRiel;
    private javax.swing.JTextField txtSub;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtcode;
    // End of variables declaration//GEN-END:variables
}
